import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  HeadingLevel,
  AlignmentType,
  ShadingType,
  Header,
  Footer,
  PageNumber,
  NumberFormat,
} from "docx";
import { IntelligenceEvidence } from "@/lib/api";

export interface DocxReportInput {
  competitor: string;
  question: string;
  summary: string;
  strategicSignal: string;
  observedChanges: string[];
  watchNext: string[];
  evidence: IntelligenceEvidence[];
  status?: string;
  confidence?: number;
}

export async function generateDocxReport(data: DocxReportInput): Promise<Buffer> {
  const currentDate = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  const analysisId =
    "CIA-" +
    (
      (Math.abs(
        data.competitor.split("").reduce((acc, c) => acc + c.charCodeAt(0), 48)
      ) %
        900) +
      100
    )
      .toString()
      .padStart(4, "0");

  const doc = new Document({
    creator: "Compete Intel Agent (CIA)",
    title: `Competitive Intelligence Report - ${data.competitor}`,
    description: `Executive intelligence report analyzing ${data.competitor}`,
    styles: {
      default: {
        document: {
          run: {
            font: "Calibri",
            size: 22, // 11pt
            color: "111827", // text-gray-900
          },
          paragraph: {
            spacing: { line: 280, after: 120 },
          },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440, // 1 inch
              bottom: 1440,
              left: 1440,
              right: 1440,
            },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: "COMPETE INTEL // STRATEGIC RECONNAISSANCE DOSSIER",
                    size: 16,
                    color: "6B7280",
                    bold: true,
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: "CONFIDENTIAL & PROPRIETARY · Generated by Compete Intel Agent  |  Page ",
                    size: 16,
                    color: "9CA3AF",
                  }),
                  new TextRun({
                    children: [PageNumber.CURRENT],
                    size: 16,
                    color: "9CA3AF",
                  }),
                  new TextRun({
                    text: " of ",
                    size: 16,
                    color: "9CA3AF",
                  }),
                  new TextRun({
                    children: [PageNumber.TOTAL_PAGES],
                    size: 16,
                    color: "9CA3AF",
                  }),
                ],
              }),
            ],
          }),
        },
        children: [
          // ── TOP BRAND TAG ──
          new Paragraph({
            children: [
              new TextRun({
                text: "COMPETE INTEL AGENT",
                bold: true,
                size: 20,
                color: "4F46E5", // Indigo accent
              }),
              new TextRun({
                text: "  |  AUTOMATED COMPETITIVE INTELLIGENCE",
                size: 18,
                color: "9CA3AF",
              }),
            ],
            spacing: { after: 160 },
          }),

          // ── MAIN REPORT TITLE ──
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [
              new TextRun({
                text: `COMPETITIVE INTELLIGENCE REPORT: ${data.competitor.toUpperCase()}`,
                bold: true,
                size: 36, // 18pt
                color: "0F172A",
              }),
            ],
            spacing: { after: 100 },
          }),

          // ── METADATA BAR TABLE ──
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            borders: {
              top: { style: BorderStyle.NONE },
              bottom: { style: BorderStyle.SINGLE, size: 4, color: "E2E8F0" },
              left: { style: BorderStyle.NONE },
              right: { style: BorderStyle.NONE },
              insideHorizontal: { style: BorderStyle.NONE },
              insideVertical: { style: BorderStyle.NONE },
            },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    children: [
                      new Paragraph({
                        children: [
                          new TextRun({ text: "ANALYSIS ID: ", bold: true, size: 18, color: "64748B" }),
                          new TextRun({ text: `#${analysisId}`, bold: true, size: 18, color: "0F172A" }),
                        ],
                      }),
                    ],
                  }),
                  new TableCell({
                    children: [
                      new Paragraph({
                        children: [
                          new TextRun({ text: "AUDIT DATE: ", bold: true, size: 18, color: "64748B" }),
                          new TextRun({ text: currentDate, size: 18, color: "0F172A" }),
                        ],
                      }),
                    ],
                  }),
                  new TableCell({
                    children: [
                      new Paragraph({
                        children: [
                          new TextRun({ text: "STATUS: ", bold: true, size: 18, color: "64748B" }),
                          new TextRun({
                            text: data.status === "LIVE" ? "LIVE INTELLIGENCE" : "SEEDED ARCHIVE",
                            bold: true,
                            size: 18,
                            color: data.status === "LIVE" ? "059669" : "4F46E5",
                          }),
                        ],
                      }),
                    ],
                  }),
                ],
              }),
            ],
          }),

          new Paragraph({ spacing: { after: 240 } }),

          // ── USER INQUIRY BLOCK ──
          new Paragraph({
            children: [
              new TextRun({
                text: "INQUIRY DIRECTIVE: ",
                bold: true,
                size: 18,
                color: "64748B",
              }),
              new TextRun({
                text: `"${data.question}"`,
                italics: true,
                size: 20,
                color: "1E293B",
              }),
            ],
            spacing: { after: 240 },
          }),

          // ── SECTION 1: EXECUTIVE SUMMARY ──
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [
              new TextRun({
                text: "1. EXECUTIVE INTELLIGENCE SUMMARY",
                bold: true,
                size: 26,
                color: "0F172A",
              }),
            ],
            spacing: { before: 200, after: 120 },
          }),

          // Executive Summary Callout Box
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            borders: {
              left: { style: BorderStyle.SINGLE, size: 24, color: "4F46E5" }, // Thick left indigo border
              top: { style: BorderStyle.SINGLE, size: 2, color: "E2E8F0" },
              right: { style: BorderStyle.SINGLE, size: 2, color: "E2E8F0" },
              bottom: { style: BorderStyle.SINGLE, size: 2, color: "E2E8F0" },
            },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    shading: { type: ShadingType.CLEAR, fill: "F8FAFC" },
                    children: [
                      new Paragraph({
                        children: [
                          new TextRun({
                            text: data.summary,
                            size: 22,
                            color: "1E293B",
                          }),
                        ],
                        spacing: { before: 100, after: 100 },
                      }),
                    ],
                  }),
                ],
              }),
            ],
          }),

          new Paragraph({ spacing: { after: 240 } }),

          // ── SECTION 2: STRATEGIC SIGNAL & INFERENCE ──
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [
              new TextRun({
                text: "2. STRATEGIC SIGNAL & INFERENCE",
                bold: true,
                size: 26,
                color: "0F172A",
              }),
            ],
            spacing: { before: 200, after: 120 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "Core Strategic Pattern: ",
                bold: true,
                color: "4F46E5",
              }),
              new TextRun({
                text: data.strategicSignal,
                size: 22,
                color: "1E293B",
              }),
            ],
            spacing: { after: 180 },
          }),

          // ── SECTION 3: OBSERVED COMPETITIVE CHANGES ──
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [
              new TextRun({
                text: "3. OBSERVED COMPETITIVE MOVES",
                bold: true,
                size: 26,
                color: "0F172A",
              }),
            ],
            spacing: { before: 200, after: 120 },
          }),
          ...data.observedChanges.map(
            (change, i) =>
              new Paragraph({
                bullet: { level: 0 },
                children: [
                  new TextRun({
                    text: `Move ${i + 1}: `,
                    bold: true,
                    color: "0F172A",
                  }),
                  new TextRun({
                    text: change,
                    color: "334155",
                  }),
                ],
                spacing: { after: 80 },
              })
          ),

          new Paragraph({ spacing: { after: 200 } }),

          // ── SECTION 4: GROUNDED EVIDENCE AUDIT TRAIL ──
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [
              new TextRun({
                text: "4. GROUNDED EVIDENCE LOG (TEMPORAL RECALL)",
                bold: true,
                size: 26,
                color: "0F172A",
              }),
            ],
            spacing: { before: 200, after: 120 },
          }),

          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            borders: {
              top: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
              bottom: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
              left: { style: BorderStyle.NONE },
              right: { style: BorderStyle.NONE },
              insideHorizontal: { style: BorderStyle.SINGLE, size: 2, color: "E2E8F0" },
              insideVertical: { style: BorderStyle.NONE },
            },
            rows: [
              // Header Row
              new TableRow({
                tableHeader: true,
                children: [
                  new TableCell({
                    shading: { type: ShadingType.CLEAR, fill: "0F172A" },
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: "DATE", bold: true, size: 18, color: "FFFFFF" })],
                      }),
                    ],
                  }),
                  new TableCell({
                    shading: { type: ShadingType.CLEAR, fill: "0F172A" },
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: "CATEGORY", bold: true, size: 18, color: "FFFFFF" })],
                      }),
                    ],
                  }),
                  new TableCell({
                    shading: { type: ShadingType.CLEAR, fill: "0F172A" },
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: "FACTUAL EVENT", bold: true, size: 18, color: "FFFFFF" })],
                      }),
                    ],
                  }),
                  new TableCell({
                    shading: { type: ShadingType.CLEAR, fill: "0F172A" },
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: "SOURCE", bold: true, size: 18, color: "FFFFFF" })],
                      }),
                    ],
                  }),
                ],
              }),
              // Data Rows
              ...data.evidence.map(
                (ev, idx) =>
                  new TableRow({
                    children: [
                      new TableCell({
                        shading: { type: ShadingType.CLEAR, fill: idx % 2 === 0 ? "FFFFFF" : "F8FAFC" },
                        children: [
                          new Paragraph({
                            children: [new TextRun({ text: ev.date, size: 18, color: "475569" })],
                          }),
                        ],
                      }),
                      new TableCell({
                        shading: { type: ShadingType.CLEAR, fill: idx % 2 === 0 ? "FFFFFF" : "F8FAFC" },
                        children: [
                          new Paragraph({
                            children: [
                              new TextRun({
                                text: ev.category.toUpperCase(),
                                bold: true,
                                size: 16,
                                color: "4F46E5",
                              }),
                            ],
                          }),
                        ],
                      }),
                      new TableCell({
                        shading: { type: ShadingType.CLEAR, fill: idx % 2 === 0 ? "FFFFFF" : "F8FAFC" },
                        children: [
                          new Paragraph({
                            children: [new TextRun({ text: ev.event, size: 18, color: "0F172A" })],
                          }),
                        ],
                      }),
                      new TableCell({
                        shading: { type: ShadingType.CLEAR, fill: idx % 2 === 0 ? "FFFFFF" : "F8FAFC" },
                        children: [
                          new Paragraph({
                            children: [new TextRun({ text: ev.source || "Public Web", size: 16, color: "64748B" })],
                          }),
                        ],
                      }),
                    ],
                  })
              ),
            ],
          }),

          new Paragraph({ spacing: { after: 240 } }),

          // ── SECTION 5: WHAT TO WATCH NEXT ──
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [
              new TextRun({
                text: "5. STRATEGIC SURVEILLANCE DIRECTIVES (WATCH NEXT)",
                bold: true,
                size: 26,
                color: "0F172A",
              }),
            ],
            spacing: { before: 200, after: 120 },
          }),
          ...data.watchNext.map(
            (item, i) =>
              new Paragraph({
                bullet: { level: 0 },
                children: [
                  new TextRun({
                    text: `Watchpoint ${i + 1}: `,
                    bold: true,
                    color: "D97706", // Amber accent
                  }),
                  new TextRun({
                    text: item,
                    color: "1E293B",
                  }),
                ],
                spacing: { after: 80 },
              })
          ),

          new Paragraph({ spacing: { after: 300 } }),

          // ── BOTTOM LINE CONCLUSION ──
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            borders: {
              top: { style: BorderStyle.SINGLE, size: 12, color: "4F46E5" },
              bottom: { style: BorderStyle.SINGLE, size: 2, color: "E2E8F0" },
              left: { style: BorderStyle.NONE },
              right: { style: BorderStyle.NONE },
            },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    shading: { type: ShadingType.CLEAR, fill: "F1F5F9" },
                    children: [
                      new Paragraph({
                        children: [
                          new TextRun({
                            text: "BOTTOM LINE SYNTHESIS: ",
                            bold: true,
                            size: 20,
                            color: "4F46E5",
                          }),
                          new TextRun({
                            text: `${data.competitor}'s trajectory demonstrates deliberate structural movement. Recommend continuous tracking of their pricing thresholds and enterprise compliance announcements.`,
                            size: 20,
                            color: "1E293B",
                          }),
                        ],
                        spacing: { before: 140, after: 140 },
                      }),
                    ],
                  }),
                ],
              }),
            ],
          }),

          new Paragraph({ spacing: { after: 200 } }),

          // ── SIGN OFF ──
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: "Generated automatically by Compete Intel Agent (CIA) · Powered by Vectorize Hindsight & Google Gemini",
                size: 16,
                italics: true,
                color: "94A3B8",
              }),
            ],
          }),
        ],
      },
    ],
  });

  return await Packer.toBuffer(doc);
}
